import { Open_Sans } from 'next/font/google';
import type { Metadata } from "next";
import "./globals.css";

const openSans = Open_Sans({
  subsets: ['latin'],
  variable: '--font-open-sans',
});

export const metadata: Metadata = {
  title: "EnhancedSearch",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${openSans.variable}`}>
        {children}
      </body>
    </html>
  );
}